
# .scrutinizer.yml

build:
  image: default-bionic

  dependencies:
    before:
      - rm composer.lock

  tests:
    override:
      -
        command: 'phpdbg -qrr vendor/bin/phpunit --coverage-clover tests/build/clover.xml'
        coverage:
          file: 'tests/build/clover.xml'
          format: 'clover'

  nodes:

    php74:
      environment:
        php: 7.4

    php80:
      environment:
        php: 8.0

    php81:
      environment:
        php: 8.1

    php82:
      environment:
        php: 8.2


checks:
  php: true


filter:
  excluded_paths:
    - tests/*

